export const API_PREFIX = "/api";

export const ROUTES = {
  AUTH: {
    BASE: `${API_PREFIX}/auth`,
    SIGNUP: "/signup",
    LOGIN: "/login",
    REQUEST_OTP: "/request-otp",
    VERIFY_OTP: "/verify-otp",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GOOGLE: "/google",
    REFRESH: "/refresh",
    CHANGE_PASSWORD: "/change-password",
    PROFILE: "/profile",
  },
  ADMIN: {
    BASE: `${API_PREFIX}/admin`,
    USERS: "/users",
    USER_BY_ID: "/users/:id",
    UNBLOCK_USER: "/users/:id/unblock",
    PROVIDERS: "/providers",
    PROVIDER_BY_ID: "/providers/:id",
    VERIFY_PROVIDER: "/providers/:id/verify",
    PROVIDER_STATUS: "/providers/:id/status",
    SERVICES: "/services",
    SERVICE_BY_ID: "/services/:id",
  },
  NOTIFICATIONS: {
    BASE: `${API_PREFIX}/notifications`,
    LIST: "/",
    MARK_READ: "/:id/read",
    MARK_ALL_READ: "/read-all",
  },
  REVIEWS: {
    BASE: `${API_PREFIX}/reviews`,
    CREATE: "/",
    BY_PROVIDER: "/provider/:providerId",
    LIKE: "/:id/like",
  },
  DASHBOARD: {
    BASE: `${API_PREFIX}/dashboard`,
    USER: "/user",
    PROVIDER: "/provider",
  },
  WALLET: {
    BASE: `${API_PREFIX}/wallet`,
    GET: "/",
  },
  PAYMENTS: {
    BASE: `${API_PREFIX}/payments`,
    CREATE_CHECKOUT: "/create-checkout-session",
    VERIFY: "/verify-payment",
    WEBHOOK: "/webhook",
  },
  PROVIDER: {
    BASE: `${API_PREFIX}/provider`,
    PROFILE: "/profile",
    AVAILABILITY: "/availability",
    ONBOARDING_PROFILE: "/onboarding/profile",
    ONBOARDING_LOCATION: "/onboarding/location",
    ONBOARDING_SERVICE: "/onboarding/service",
    ONBOARDING_DOCUMENTS: "/onboarding/documents",
    ONBOARDING_BANK: "/onboarding/bank",
    ONBOARDING_RESET: "/onboarding/reset",
  },
  BOOKINGS: {
    BASE: `${API_PREFIX}/bookings`,
    SLOTS: "/slots",
    CREATE: "/",
    LIST: "/",
    PROVIDER_LIST: "/provider",
    DETAIL: "/:id",
    CANCEL: "/:id/cancel",
    RESCHEDULE: "/:id/reschedule",
    ACCEPT: "/:id/accept",
    CONFIRM: "/:id/confirm",
    COMPLETE: "/:id/complete",
    OTP_ARRIVAL_GENERATE: "/:id/otp/arrival/generate",
    OTP_ARRIVAL_VERIFY: "/:id/otp/arrival/verify",
    OTP_COMPLETION_GENERATE: "/:id/otp/completion/generate",
    OTP_COMPLETION_VERIFY: "/:id/otp/completion/verify",
  },
  ADDRESS: {
    BASE: `${API_PREFIX}/addresses`,
    LIST: "/",
    CREATE: "/",
    UPDATE: "/:id",
    DELETE: "/:id",
    SET_DEFAULT: "/:id/default",
  },
  CHAT: {
    BASE: `${API_PREFIX}/chat`,
    CONVERSATIONS: "/conversations",
    CONVERSATION_BY_ID: "/conversations/:conversationId",
    HISTORY: "/:bookingId",
    MARK_READ: "/:bookingId/read",
  },
} as const;