export const API_PREFIX = "/api";

export const ROUTES = {
  AUTH: {
    BASE: `${API_PREFIX}/auth`,
    SIGNUP: "/signup",
    LOGIN: "/login",
    VERIFY_OTP: "/verify-otp",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GOOGLE: "/google",
    REFRESH: "/refresh",
    CHANGE_PASSWORD: "/change-password",
    PROFILE: "/profile",
  },
  ADMIN: {
    BASE: `${API_PREFIX}/admin`,
    USERS: "/users",
    USER_STATUS: "/users/:id/status",
    USER_UNBLOCK: "/users/:id/unblock",
    USER_BY_ID: "/users/:id",
    PROVIDERS: "/providers",
    PROVIDERS_PENDING: "/providers/pending",
    PROVIDER_BY_ID: "/providers/:id",
    PROVIDER_VERIFICATION: "/providers/:providerId/verification",
    SERVICES: "/services",
    SERVICE_BY_ID: "/services/:id",
    DASHBOARD_STATS: "/dashboard/stats",
    DASHBOARD_REVENUE: "/dashboard/revenue",
    DASHBOARD_USER_GROWTH: "/dashboard/user-growth",
    REPORTS: "/reports",
    REPORT_RESOLVE: "/reports/:reportId/resolve",
    ALL_BOOKINGS: "/bookings",
    BOOKING_BY_ID: "/bookings/:id",
  },
  NOTIFICATIONS: {
    BASE: `${API_PREFIX}/notifications`,
    LIST: "/",
    MARK_READ: "/:id/read",
    MARK_ALL_READ: "/read-all",
  },
  REVIEWS: {
    BASE: `${API_PREFIX}/reviews`,
    CREATE: "/",
    BY_PROVIDER: "/provider/:providerId",
    LIKE: "/:id/like",
  },
  DASHBOARD: {
    BASE: `${API_PREFIX}/dashboard`,
    USER: "/user",
    PROVIDER: "/provider",
  },
  WALLET: {
    BASE: `${API_PREFIX}/wallet`,
    GET: "/",
  },
  PAYMENTS: {
    BASE: `${API_PREFIX}/payments`,
    WEBHOOK: "/webhook",
    CREATE_CHECKOUT: "/create-checkout-session",
    VERIFY: "/verify-payment",
    WALLET_PAY: "/wallet-pay",
  },
  PROVIDER: {
    BASE: `${API_PREFIX}/provider`,
    PROFILE: "/profile",
    LOCATION: "/location",
    SERVICE_DETAILS: "/service-details",
    VERIFY_DOCS: "/verify-docs",
    BANK_DETAILS: "/bank-details",
    REAPPLY: "/reapply",
    AVAILABILITY: "/availability",
  },
  BOOKINGS: {
    BASE: `${API_PREFIX}/bookings`,
    SLOTS: "/slots",
    CREATE: "/",
    MY_BOOKINGS: "/my-bookings",
    PROVIDER_JOBS: "/provider/my-jobs",
    DETAIL: "/detail/:bookingId",
    CANCEL: "/:bookingId/cancel",
    RESCHEDULE: "/:bookingId/reschedule",
    ACCEPT_RESCHEDULE: "/:bookingId/accept-reschedule",
    REJECT_RESCHEDULE: "/:bookingId/reject-reschedule",
    ACCEPT: "/:bookingId/accept",
    STATUS: "/:bookingId/status",
    PROVIDER_CANCEL: "/:bookingId/provider-cancel",
    PROVIDER_RESCHEDULE: "/:bookingId/provider-reschedule",
    ARRIVAL_OTP_GENERATE: "/:bookingId/arrival-otp/generate",
    ARRIVAL_OTP_VERIFY: "/:bookingId/arrival-otp/verify",
    COMPLETION_OTP_GENERATE: "/:bookingId/completion-otp/generate",
    COMPLETION_OTP_VERIFY: "/:bookingId/completion-otp/verify",
  },
  ADDRESS: {
    BASE: `${API_PREFIX}/addresses`,
    LIST: "/",
    CREATE: "/",
    UPDATE: "/:id",
    DELETE: "/:id",
    SET_DEFAULT: "/:id/default",
  },
  CHAT: {
    BASE: `${API_PREFIX}/chat`,
    UPLOAD_IMAGE: "/upload-image",
    CONVERSATIONS: "/conversations",
    CONVERSATION_BY_ID: "/conversations/:conversationId",
    MESSAGE_BY_ID: "/messages/:messageId",
    HISTORY: "/:conversationId",
    MARK_READ: "/:conversationId/read",
    MARK_DELIVERED: "/delivered",
  },
  REPORTS: {
    BASE: `${API_PREFIX}/reports`,
    CREATE: "/",
    MY_REPORTS: "/my",
    ALL: "/all",
    BY_ID: "/:id",
    ACTION: "/:id/action",
  },
  SERVICES: {
    BASE: `${API_PREFIX}/services`,
    LIST: "/",
    PROVIDERS: "/providers",
  },
  PROVIDERS: {
    BASE: `${API_PREFIX}/providers`,
    LIST: "/",
  },
} as const;